### ISSUE TITLE
Add board schematics and BOM to REV20180717B

### ISSUE THREAD

**Issue by elsevers** [WEMPEC/AMDC-Hardware#20]
Add the REV20180717B board schematics and bill of materials to the archived REV20180717B folder.

**Note:** REVB had been added as a zip file. Going forward, let's use uncompressed folders to house the revision releases.

**Comment by npetersen2** [comment]
Schematics have been added to REV20180717B archive, but not BOM. Since REV2 is already built, we are looking to REV3 next. No need to add BOM at this point.
