### ISSUE TITLE
Switch User I/O connections from MIO bank 500 to 501

### ISSUE THREAD

**Issue by jtcomp** [WEMPEC/AMDC-Hardware#24]
The eMMC currently shares the MIO bank 500 (MIO 0 , 15:9) with some of the user I/O and the eMMC is by default connected. Many of the Bank 501 MIO pins are currently unsued (MIO 51:40), and the user I/O nets could be connected there instead.

**Comment by npetersen2** [comment]
I agree this should be done... The only issue is that routing was much easier to MIO bank 500, not 501.

From what I can tell, the eMMC will be used to boot board eventually (non-volatile; can just power-up and go). I think it is only used for booting, so in theory, it is fine to share pins with user I/O, but just to be safe, probably should move to MIO bank 501, as they are unused anyway.

**Comment by npetersen2** [comment]
Moved to bank 501 MIO pins.
