### ISSUE TITLE
Consider power sequencing to fix inrush current issues

### ISSUE THREAD

**Issue by npetersen2** [WEMPEC/AMDC-Hardware#35]
Reduced bulk capacitance on VIN to 1000uF. This solved PicoZed "blinky" issue (reduced inrush current).

"If I have the powerstack connected when I power the AMDC up, the inrush from the powerstack seems to still be causing blinky. May need to implement some sort of power sequencing on rev 3. I'll think about it" -Jason.

This issue serves as a reminder for this problem.

**Comment by jjsylvestre** [comment]
Powered up board, then connected 5V5 jumper per Eric's recommendation. Same results - blinky

**Comment by jjsylvestre** [comment]
Inrush current on 5V5 node
![lecroy5](https://user-images.githubusercontent.com/16614893/46306504-142d5f80-c57a-11e8-9ead-1080d7aba1cc.jpg)

**Comment by jjsylvestre** [comment]
Solved problem by adding 2ohm resistor inline with 5V5 node to limit inrush current

![img-4465](https://user-images.githubusercontent.com/16614893/46308069-450f9380-c57e-11e8-8467-4450fa8236b8.JPG)

**Comment by npetersen2** [comment]
@jjsylvestre Can you decide how we should fix this on REV C and file a bug issue describing what should be done (and close this issue)? Thanks.

**Comment by jjsylvestre** [comment]
See Issue #43 for continued conversation on this
