### ISSUE TITLE
Verify Ethernet works

### ISSUE THREAD

**Issue by npetersen2** [WEMPEC/AMDC-Hardware#40]
Ethernet PHY is located on PicoZed SoM, so AMDC just routes out signals to a RJ45 receptacle.

Prove that this works by loading in lwIP IP into Vivado and do a simple networking project. Just a ping is all that's really needed.

**Comment by jtcomp** [comment]
Ethernet is verified to work.

I created a Vivado project, enabled the "Ethernet 0" on the MIO. Using the SDK, I created a new project using the default IwIP Echo Server test, and a BSP with IsIP included. 

The IP, gateway and subnet used have to be the same network address & subnet as shown on the output of `ipconfig`.

The echo test simply echos any packet coming in, which I connected to using the `telnet` function in Windows command prompt.
