### ISSUE TITLE
Too much inrush current on 5V5 from Picozed

### ISSUE THREAD

**Issue by jjsylvestre** [WEMPEC/AMDC-Hardware#42]
Proposed solution is current limiting resistor with SPST relay in parallel that close from an enable signal from the PicoZed

**Comment by jjsylvestre** [comment]
![image](https://user-images.githubusercontent.com/16614893/46362183-333cf780-c635-11e8-8ec8-ebd1ff64df75.png)

**Comment by npetersen2** [comment]
Talked with @jjsylvestre:

Would like the PZ_ENABLE signal in above picture to not be controlled from software, but instead in h/w.

Our idea: use a RC circuit with time constant of ~1 sec, feeding into a comparator, which then drives a n-channel MOSFET to enable relay, thus shorting out inrush limiting resistor.

I'll implement this idea and post again for discussion.

**Comment by npetersen2** [comment]
**Proposed implementation:**
![image](https://user-images.githubusercontent.com/20168990/48514127-2f4ee880-e823-11e8-835b-5dd459962fb9.png)

Need to pick relay to use, add flyback diode, and add LED to indicate when resistor is inline.

@jjsylvestre thoughts?

**Comment by npetersen2** [comment]
Thinking that main resistor should be 2 ohms (not 1), due to power supply limit of 3A at 5.5V.

This would limit current to 2.75A, and require a (2.75)^2 * 2 = ~15W resistor... Pretty beefy.

**Comment by jjsylvestre** [comment]
Looks good.  Looks like comparator is TTL output. Are you 100% certain that when IN+ > IN-, that corresponds to a high output? Couldn't find that info in the ds. 

As for the power value of the resistor, we can probably some get away with something lower since the current is exponentially decaying with time. 

Also, we might want to take a look at the 5V rail during the startup event to see how stable it is.

**Comment by npetersen2** [comment]
- Changed comparator to one that specified its output level vs. input voltages (LMV761MAX/NOPB)
- Added flyback diode
- Using four 2512 SMD 6.8R resistors in parallel to achieve high max power, while being cheap and relatively small footprint.


![image](https://user-images.githubusercontent.com/20168990/48637635-e8343500-e993-11e8-9934-1043ef787e04.png)

**Comment by npetersen2** [comment]
Last thing is to check 5V rail during startup to see that it is stable enough to use for cap charging / timing. Will update issue with results.

**Comment by npetersen2** [comment]
Plot of 24V board input (C2) vs. 5V rail (C1) during startup. Looks good to me.

![24v vs 5v startup](https://user-images.githubusercontent.com/20168990/48638383-0bf87a80-e996-11e8-97fe-ffaf13518cd1.jpg)

**Comment by npetersen2** [comment]
Reopening for investigation on not using mechanical relay. Maybe use BJT? Currently looking up ANs for ideas. 

See this article about why FPGA startup is typically an issue for power supplies:
http://www.ti.com/lit/an/slyt079/slyt079.pdf

**Comment by npetersen2** [comment]
This paper describes how to design MOSFET-based inrush current limiter:
http://www.mosaic-industries.com/embedded-systems/_media/pdfs/application-notes/motorola-an1542-active-inrush-current-limiter.pdf

**Comment by npetersen2** [comment]
Final implementation: using TPS22965 (http://www.ti.com/lit/ds/symlink/tps22965.pdf), costs $1.

This is a 5.7-V, 6-A, 16-mΩ On-Resistance Load Switch. Basically just an n-channel MOSFET which has an adjustable slew rate for turn on.

This slew rate determines inrush current. I think the only capacitance on the 5.5V node is the bypass caps for the LDOs. Therefore, this is 50uF. I calculated values resulting in inrush of ~700mA.

![image](https://user-images.githubusercontent.com/20168990/48665829-0b85df80-ea7b-11e8-806e-26226c5fcc5c.png)
